packages:
  - .
  - puller

ignoredBuiltDependencies:
  - electron

onlyBuiltDependencies:
  - esbuild
  - '@tailwindcss/oxide'
  - core-js

allowBuilds:
  esbuild: true
  '@tailwindcss/oxide': true
  core-js: true
