#!/usr/bin/env node
/**
 * Embed runtime text assets into puller/src/embedded/assets.generated.ts
 * so the pkg sidecar does not need filesystem reads (Flatpak-safe).
 */
import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const pullerRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = path.resolve(pullerRoot, '..');

const assets = [
	{
		exportName: 'UNITY_INJECT_SOURCE',
		file: path.join(repoRoot, 'static/unity/inject.js'),
		label: 'static/unity/inject.js'
	},
	{
		exportName: 'GAME_STORAGE_BRIDGE_SOURCE',
		file: path.join(repoRoot, 'static/game-storage-bridge.child.js'),
		label: 'static/game-storage-bridge.child.js'
	}
];

const lines = [
	'/* eslint-disable */',
	'/** Generated by puller/scripts/embed-assets.mjs — do not edit. */',
	''
];

for (const asset of assets) {
	const text = readFileSync(asset.file, 'utf8');
	lines.push(`/** Inlined from ${asset.label} */`);
	lines.push(`export const ${asset.exportName} = ${JSON.stringify(text)};`);
	lines.push('');
}

const outDir = path.join(pullerRoot, 'src/embedded');
mkdirSync(outDir, { recursive: true });
const outFile = path.join(outDir, 'assets.generated.ts');
writeFileSync(outFile, lines.join('\n'));
console.log(`[embed-assets] wrote ${path.relative(repoRoot, outFile)} (${assets.length} assets)`);
